name: Python Unit Test Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
      - master
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.14'  # Use the desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/bibler/testApp/requirements.txt  # Install dependencies listed in requirements.txt

    # Step 4: Run unit tests
    - name: Run Unit Tests
      run: |
        python -m unittest discover -s ./src/bibler/testApp # Discover and run unit tests in the 'tests' directory

    # Step 5: Upload test results (optional, for analysis on GitHub)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: unittest-results
        path: test-results.xml  # Adjust this to match your test result file if needed

